### PR TITLE
build: add Nx

### LINKED ISSUE #342: migrate to nrwl / nx
Seems that a "simple" migration isn't working now that this repo has already 6 sub "libraries" .. but sooner or later this needs to be converted to that.

If anyone wants to tackle this, please do, this would help alot!

### PR DESCRIPTION
**Pull request by brandonroberts**
This integrates [Nx](https://nx.dev) into the monorepo to manage the build tooling.

- All `ng` commands are handled by `nx`
- All existing commands work the same (build/test/e2e)
- Local computation caching is enabled

Closes #342

### CODE REVIEW

**Comment by negue** [comment]
Wooooot!!! awesome 🤩 

THANK YOU!!

Did you used any of the existing schematics to convert it to nx or was this all done by hand? :O

**Comment by brandonroberts** [comment]
> Wooooot!!! awesome 🤩
> 
> THANK YOU!!
> 
> Did you used any of the existing schematics to convert it to nx or was this all done by hand? :O

It was a mix of both 😅. You have multiple projects already, and the existing one to migrate to an Nx workspace currently only supports one project. So I ran

`npx add-nx-to-monorepo` to add the initial Nx config

Then I took all but one project out of the angular.json and ran

`ng add @nrwl/workspace --preserveAngularCLILayout`

To fix the Angular config. After that, it was tweaking some of the config files to reference `tsconfig.base.json` to make sure everything was still working as-is.

If it were a single project Angular CLI project, I would just use

`ng add @nrwl/workspace --preserveAngularCLILayout`

And remove the `newProjectRoot` from the `angular.json`

**Comment by brandonroberts** [comment]
It did surface some circular dependencies but you probably already knew about those. I did have to turn off automatically building all the dependencies

**Comment by negue** [comment]
> It was a mix of both 😅. You have multiple projects already, and the existing one to migrate to an Nx workspace currently only supports one project. So I ran
> 
> `npx add-nx-to-monorepo` to add the initial Nx config
> 
> Then I took all but one project out of the angular.json and ran
> 
> `ng add @nrwl/workspace --preserveAngularCLILayout`
> 
> To fix the Angular config. After that, it was tweaking some of the config files to reference `tsconfig.base.json` to make sure everything was still working as-is.
> 
> If it were a single project Angular CLI project, I would just use
> 
> `ng add @nrwl/workspace --preserveAngularCLILayout`
> 
> And remove the `newProjectRoot` from the `angular.json`

Woah .... this should be a blog post :D or if it already exist - I couldn't find it!

Thank you for the PR! This will really help as base for more awesome nrwl stuff to add.

> It did surface some circular dependencies but you probably already knew about those. I did have to turn off automatically building all the dependencies

I saw some but yes those will probably the first things to add now like also adding more lints ... so there is still lots more to go haha


Would you like to be also added to the contributors list on the readme?

**Comment by brandonroberts** [comment]
Sure I don't mind being added. A blog post is on the list! 😁

**Comment by negue** [comment]
> Sure I don't mind being added. 

Awesome! @all-contributors please add @brandonroberts for code

> A blog post is on the list! 😁

Hehe, perfect! 😁

**Pull request merged**
