### PR TITLE
Added first draft icon for issue #11

### PR DESCRIPTION
**Pull request by CrypticEngima**
Samples of first draft icon
Meme-Box - 512x512

Meme-Box - 512x512 - Transparent

### CODE REVIEW

**Comment by negue** [comment]
This is awesome!!! Great idea haha, I never what kind of icon I'd choose for meme-box but that makes it perfect. 🎉 

Could you color the box itself, so that this will be fully visible.

Could you color each of the stars / hexagons in a different color too?

Everything else could stay  transparent, which hopefully makes a nice effect as a desktop icon

**Comment by CrypticEngima** [comment]
What Are your thoughts on this

Meme-Box - 512x512 - Transparent - ColorStars

**Comment by CrypticEngima** [comment]
@negue missed a comment from you about coloring the box so i used Twitch Purple for the box in this one

Meme-Box - 512x512 - Transparent - FullColor

**Comment by CrypticEngima** [comment]
Sample of new Icon

Meme-Box - 512x512 - Transparent - FullColor-whitebox

**Comment by CrypticEngima** [comment]
Updated to fix inconsistancies

Meme-Box - 512x512 - Transparent - FullColor-whitebox

**Comment by negue** [comment]
Thank you!!!! this will look great. I'll try to use the svg and maybe replace the box fill color but other than this is freaking amazing.


I couldn't wrap my head around on how an icon should look like but this just answered it for me. 🎉

**Comment by negue** [comment]
@all-contributors please add @CrypticEngima for design

**Pull request merged**
