### PR TITLE
Refactoring screen-arrange Part 2: Preview

### PR DESCRIPTION
**Pull request by owehmer**
After #251 it's now time to give the good old preview it's own home. ❤️

### CODE REVIEW

**Comment by owehmer** [comment]
As a sidenote: I think you should create a general CSS class file where you can drop stuff like `.hidden`.

**Comment by owehmer** [comment]
I just found a bug where when you first select an item (without prior seleciton) the selection rectangle is in a weird position
image

**Comment by owehmer** [comment]
Okay, I fixed it by giving the top bar a fixed height. this also helps with the `gewd-autoscale` moving a few pixels to the top or bottom if you click on an element multiple times (has been there before my refactoring)

**Comment by negue** [comment]
> As a sidenote: I think you should create a general CSS class file where you can drop stuff like .hidden.

will do today

> I just found a bug where when you first select an item (without prior seleciton) the selection rectangle is in a weird position

yeah it happens when the panels are showed ... 


> Okay, I fixed it by giving the top bar a fixed height. this also helps with the gewd-autoscale moving a few pixels to the top or bottom if you click on an element multiple times (has been there before my refactoring)


checking the site preview / review  now

**Comment by negue** [comment]
Amazing how much code ended up in the arrange dialog :D :D 

It seems the selected border is gone again? atleast on the preview.

Otherwise its LGTM

**Comment by negue** [comment]
Thank you for refactoring these out - it really helps so I can focus on other stuff in the meantime :)

**Pull request merged**
